default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: eduflow_development
  username: postgres
  password: Takudzwa95!
  host: localhost
  port: 5432

test:
  <<: *default
  database: eduflow_test
  username: postgres
  password: Takudzwa95!
  host: localhost
  port: 5432

production:
  <<: *default
  database: eduflow_production
  username: cpl_app
  password: <%= ENV["RUBY_RECIPE_APP_DATABASE_PASSWORD"] %>
